name: push
permissions:
  contents: read
on:
  push:
    branches:
      - main
jobs:
  integrate:
    uses: ./.github/workflows/integrate.yml
  document:
    permissions:
      pages: write
      id-token: write
    uses: umts/shared-workflows/.github/workflows/pages-vitepress.yml@main
